### ISSUE TITLE
Is this repo(s) free to use?

### ISSUE THREAD

**Issue by HamedMasafi** [Skycoder42/action-setup-qt#3]
Hi @Skycoder42 

I'm interesting to your works and I want to build my lib on github actions. Am I allowed to using action-setup-qt and action-upload-release for that? I'm new to github actions and it's hard to me makins ci/cd working fine. Do you have any simple sample to begin?

BR

Hamed Masafi

**Comment by Skycoder42** [comment]
As you can see, the library uses the BSD3-License (https://github.com/Skycoder42/action-setup-qt/blob/master/LICENSE) So as long as you comply to that license, yes, you can use it. For a short overview of the license, see https://tldrlegal.com/license/bsd-3-clause-license-(revised)
