### ISSUE TITLE
Adding feature 

### ISSUE THREAD

**Issue by HamedMasafi** [Skycoder42/action-setup-qt#4]
How can I add a feature to installed Qt?
Looks like there are missing feature in the build Qt version:

`D:\a\QtAseman\QtAseman\.cache\qt\include\QtCore\qfilesystemwatcher.h(45): error C2338: Required feature filesystemwatcher for file D:\a\QtAseman\QtAseman\.cache\qt\include\QtCore\qfilesystemwatcher.h not available.`

[https://github.com/HamedMasafi/QtAseman/actions/runs/209642072](https://github.com/HamedMasafi/QtAseman/actions/runs/209642072)

**Comment by Skycoder42** [comment]
Features are part of the Qt build - this action only downloads Qt from the official Website. This is nothing I can influence. You would have to convince the Qt guys to enable this feature in their builds
